project_id = "buvhdqpbpbwpzidzmdqh"

[functions.create-store-admin]
verify_jwt = false

[functions.google-product-feed]
verify_jwt = false

[functions.og-meta]
verify_jwt = false

[functions.correios-shipping]
verify_jwt = false

[functions.sync-prices]
verify_jwt = false

[functions.criar-pedido]
verify_jwt = false